import { useState, useRef } from 'react';
import { type FormKB } from '../data/knowledgeBase';
import { IconUpload, IconCheck, IconZap, IconArrowRight } from './Icons';

interface AutoFillFormProps {
    form: FormKB;
}

interface FormField {
    label: string;
    value: string;
    isCritical: boolean;
    warning?: string;
    confirmed: boolean;
}

export default function AutoFillForm({ form }: AutoFillFormProps) {
    const [step, setStep] = useState<'upload' | 'processing' | 'review' | 'done'>('upload');
    const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);
    const [dragOver, setDragOver] = useState(false);
    const [formFields, setFormFields] = useState<FormField[]>([]);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleFiles = (files: FileList) => {
        const arr = Array.from(files);
        setUploadedFiles(prev => [...prev, ...arr]);
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        setDragOver(false);
        if (e.dataTransfer.files.length) handleFiles(e.dataTransfer.files);
    };

    const processDocuments = () => {
        if (uploadedFiles.length === 0) return;
        setStep('processing');
        setTimeout(() => {
            // Simulate extracted & auto-filled fields from uploaded docs
            const mockFields: FormField[] = [
                { label: 'Applicant Full Name', value: 'Kavitha Reddy', isCritical: false, confirmed: false },
                { label: 'Father\'s / Husband\'s Name', value: 'Rami Reddy', isCritical: false, confirmed: false },
                { label: 'Date of Birth', value: '12/08/1990', isCritical: true, warning: 'Verify exactly against Aadhaar card.', confirmed: false },
                { label: 'Aadhaar Number', value: '8734 XXXX 1234', isCritical: true, warning: 'Sensitive field — confirm before submission.', confirmed: false },
                { label: 'Mobile Number', value: '9876543210', isCritical: false, confirmed: false },
                { label: 'Address', value: '14-2-45, Rajiv Nagar, Vijayawada, AP - 520001', isCritical: false, confirmed: false },
                ...form.criticalFields.map(cf => ({
                    label: cf.field,
                    value: '[Auto-extracted — please verify]',
                    isCritical: true,
                    warning: cf.warning,
                    confirmed: false,
                })),
            ];
            setFormFields(mockFields);
            setStep('review');
        }, 2800);
    };

    const toggleConfirm = (idx: number) => {
        setFormFields(prev => prev.map((f, i) => i === idx ? { ...f, confirmed: !f.confirmed } : f));
    };

    const updateValue = (idx: number, val: string) => {
        setFormFields(prev => prev.map((f, i) => i === idx ? { ...f, value: val } : f));
    };

    const canSubmit = formFields.length > 0 && formFields.filter(f => f.isCritical).every(f => f.confirmed);

    const downloadForm = () => {
        // Simulate download
        const content = formFields.map(f => `${f.label}: ${f.value}`).join('\n');
        const blob = new Blob([`=== ${form.name} — Auto-filled Draft ===\n\n${content}\n\nGenerated by SevaSetu AI`], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${form.id}-filled.txt`;
        a.click();
        URL.revokeObjectURL(url);
        setStep('done');
    };

    return (
        <div style={{ display: 'flex', flexDirection: 'column', height: '100%', padding: '1.5rem', overflowY: 'auto' }} className="chat-scroll">
            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.25rem' }}>
                <div style={{ width: 40, height: 40, borderRadius: '12px', background: 'rgba(245,158,11,0.15)', border: '1px solid rgba(245,158,11,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <IconZap size={20} color="#f59e0b" />
                </div>
                <div>
                    <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '1rem', fontWeight: 700, color: 'var(--clr-text-primary)' }}>Auto-Fill Form</h3>
                    <p style={{ fontSize: '0.78rem', color: 'var(--clr-text-muted)' }}>Upload documents to auto-fill {form.name}</p>
                </div>
            </div>

            {/* Progress steps */}
            <div style={{ display: 'flex', gap: '0.4rem', marginBottom: '1.5rem' }}>
                {(['upload', 'processing', 'review', 'done'] as const).map((s, i) => (
                    <div key={s} style={{ flex: 1, height: '4px', borderRadius: '2px', background: step === s || (['processing', 'review', 'done'].includes(step) && i < (['upload', 'processing', 'review', 'done'].indexOf(step))) ? '#f59e0b' : 'var(--clr-border-2)', transition: 'background 0.4s ease' }} />
                ))}
            </div>

            {/* STEP 1: Upload */}
            {step === 'upload' && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                    <p style={{ fontSize: '0.85rem', color: 'var(--clr-text-secondary)', lineHeight: 1.6 }}>
                        Upload your proof documents (Aadhaar, Ration Card, etc.) and the AI will extract information to auto-fill this form.
                    </p>

                    {/* Required docs reminder */}
                    <div style={{ padding: '0.85rem 1rem', borderRadius: '12px', background: 'rgba(79,142,247,0.08)', border: '1px solid rgba(79,142,247,0.2)' }}>
                        <div style={{ fontWeight: 600, fontSize: '0.82rem', color: 'var(--clr-primary)', marginBottom: '0.4rem' }}>Required Documents</div>
                        {form.requiredDocuments.map((d, i) => (
                            <div key={i} style={{ fontSize: '0.8rem', color: 'var(--clr-text-secondary)', display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.2rem' }}>
                                <span style={{ width: 5, height: 5, borderRadius: '50%', background: 'var(--clr-primary)', flexShrink: 0 }} />
                                {d}
                            </div>
                        ))}
                    </div>

                    {/* Drop zone */}
                    <div
                        onClick={() => fileInputRef.current?.click()}
                        onDragOver={e => { e.preventDefault(); setDragOver(true); }}
                        onDragLeave={() => setDragOver(false)}
                        onDrop={handleDrop}
                        style={{
                            border: `2px dashed ${dragOver ? '#f59e0b' : uploadedFiles.length ? '#10b981' : 'var(--clr-border-2)'}`,
                            borderRadius: '16px',
                            padding: '1.75rem',
                            textAlign: 'center',
                            cursor: 'pointer',
                            background: dragOver ? 'rgba(245,158,11,0.05)' : 'var(--clr-surface)',
                            transition: 'all 0.2s ease',
                        }}
                    >
                        <input ref={fileInputRef} type="file" accept="image/*,.pdf" multiple style={{ display: 'none' }} onChange={e => { if (e.target.files) handleFiles(e.target.files); }} />
                        <div style={{ width: 48, height: 48, borderRadius: '14px', background: 'rgba(245,158,11,0.12)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 0.75rem' }}>
                            <IconUpload size={22} color="#f59e0b" />
                        </div>
                        <p style={{ fontWeight: 600, fontSize: '0.9rem', color: 'var(--clr-text-primary)', marginBottom: '0.25rem' }}>Drop supporting documents</p>
                        <p style={{ fontSize: '0.78rem', color: 'var(--clr-text-muted)' }}>JPG, PNG, PDF — Multiple files allowed</p>
                    </div>

                    {/* Uploaded files list */}
                    {uploadedFiles.length > 0 && (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                            {uploadedFiles.map((f, i) => (
                                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 0.75rem', borderRadius: '8px', background: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.2)' }}>
                                    <IconCheck size={14} color="#10b981" />
                                    <span style={{ fontSize: '0.82rem', color: 'var(--clr-text-primary)', flex: 1 }}>{f.name}</span>
                                    <span style={{ fontSize: '0.72rem', color: 'var(--clr-text-muted)' }}>{(f.size / 1024).toFixed(0)}KB</span>
                                    <button onClick={(e) => { e.stopPropagation(); setUploadedFiles(prev => prev.filter((_, fi) => fi !== i)); }} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--clr-text-muted)', fontSize: '1rem', lineHeight: 1, padding: '0 2px' }}>×</button>
                                </div>
                            ))}
                        </div>
                    )}

                    <button
                        onClick={processDocuments}
                        disabled={uploadedFiles.length === 0}
                        className="btn btn-primary"
                        style={{ width: '100%', justifyContent: 'center', opacity: uploadedFiles.length === 0 ? 0.5 : 1, cursor: uploadedFiles.length === 0 ? 'not-allowed' : 'pointer' }}
                    >
                        <IconZap size={16} /> Extract & Auto-Fill
                    </button>
                </div>
            )}

            {/* STEP 2: Processing */}
            {step === 'processing' && (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', flex: 1, gap: '1.5rem', padding: '2rem' }}>
                    <div style={{ width: 72, height: 72, borderRadius: '20px', background: 'rgba(245,158,11,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                        <div style={{ width: 36, height: 36, border: '3px solid rgba(245,158,11,0.3)', borderTop: '3px solid #f59e0b', borderRadius: '50%', animation: 'spin 0.9s linear infinite' }} />
                    </div>
                    <div style={{ textAlign: 'center' }}>
                        <p style={{ fontWeight: 700, fontSize: '1rem', color: 'var(--clr-text-primary)', marginBottom: '0.4rem' }}>AI Processing Documents</p>
                        <p style={{ fontSize: '0.85rem', color: 'var(--clr-text-secondary)' }}>Extracting text, identifying fields, matching to {form.name}...</p>
                    </div>
                    <div style={{ display: 'flex', gap: '0.4rem' }}>
                        {[0, 1, 2].map(i => <span key={i} style={{ width: 8, height: 8, borderRadius: '50%', background: '#f59e0b', animation: 'blink 1.2s ease infinite', animationDelay: `${i * 0.25}s` }} />)}
                    </div>
                </div>
            )}

            {/* STEP 3: Review */}
            {step === 'review' && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.9rem', animation: 'fadeInUp 0.4s ease' }}>
                    <div style={{ padding: '0.75rem 1rem', borderRadius: '10px', background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.25)', fontSize: '0.82rem', color: '#f59e0b', fontWeight: 600 }}>
                        ✓ {formFields.length} fields extracted — please confirm critical fields (⚠️) before downloading
                    </div>

                    {formFields.map((field, i) => (
                        <div key={i} style={{
                            borderRadius: '12px',
                            border: `1px solid ${field.isCritical ? 'rgba(245,158,11,0.3)' : 'var(--clr-border)'}`,
                            background: field.isCritical ? 'rgba(245,158,11,0.04)' : 'var(--clr-surface)',
                            overflow: 'hidden',
                            transition: 'all 0.2s',
                        }}>
                            <div style={{ padding: '0.65rem 0.9rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--clr-border)' }}>
                                <span style={{ fontSize: '0.8rem', fontWeight: 600, color: field.isCritical ? '#f59e0b' : 'var(--clr-text-secondary)', display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                                    {field.isCritical && '⚠️ '}{field.label}
                                </span>
                                {field.isCritical && (
                                    <button
                                        onClick={() => toggleConfirm(i)}
                                        style={{
                                            padding: '0.25rem 0.6rem', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-body)',
                                            background: field.confirmed ? 'rgba(16,185,129,0.15)' : 'rgba(245,158,11,0.12)',
                                            border: `1px solid ${field.confirmed ? 'rgba(16,185,129,0.3)' : 'rgba(245,158,11,0.3)'}`,
                                            color: field.confirmed ? '#10b981' : '#f59e0b',
                                            transition: 'all 0.2s',
                                        }}
                                    >
                                        {field.confirmed ? '✓ Confirmed' : 'Confirm'}
                                    </button>
                                )}
                            </div>
                            <div style={{ padding: '0.5rem 0.9rem' }}>
                                <input
                                    value={field.value}
                                    onChange={e => updateValue(i, e.target.value)}
                                    style={{
                                        width: '100%', background: 'transparent', border: 'none', outline: 'none',
                                        color: 'var(--clr-text-primary)', fontSize: '0.88rem', fontFamily: 'var(--font-body)',
                                    }}
                                />
                            </div>
                            {field.warning && field.isCritical && (
                                <div style={{ padding: '0 0.9rem 0.55rem', fontSize: '0.75rem', color: '#f59e0b', opacity: 0.85 }}>{field.warning}</div>
                            )}
                        </div>
                    ))}

                    <button
                        onClick={downloadForm}
                        disabled={!canSubmit}
                        className="btn btn-primary"
                        style={{ width: '100%', justifyContent: 'center', marginTop: '0.5rem', opacity: canSubmit ? 1 : 0.5, cursor: canSubmit ? 'pointer' : 'not-allowed' }}
                    >
                        <IconArrowRight size={16} /> Download Filled Form
                    </button>
                    {!canSubmit && (
                        <p style={{ fontSize: '0.78rem', color: 'var(--clr-text-muted)', textAlign: 'center' }}>
                            Please confirm all ⚠️ critical fields before downloading
                        </p>
                    )}
                </div>
            )}

            {/* STEP 4: Done */}
            {step === 'done' && (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', flex: 1, gap: '1.25rem', padding: '2rem', textAlign: 'center', animation: 'scaleIn 0.4s ease' }}>
                    <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'rgba(16,185,129,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                        <IconCheck size={32} color="#10b981" />
                    </div>
                    <div>
                        <p style={{ fontWeight: 700, fontSize: '1.1rem', color: 'var(--clr-text-primary)', marginBottom: '0.5rem' }}>Form Downloaded!</p>
                        <p style={{ fontSize: '0.87rem', color: 'var(--clr-text-secondary)', maxWidth: '280px', lineHeight: 1.6 }}>
                            Your filled {form.name} draft has been saved. Submit it at: <strong style={{ color: 'var(--clr-primary)' }}>{form.submissionLocation}</strong>
                        </p>
                    </div>
                    <button
                        onClick={() => { setStep('upload'); setUploadedFiles([]); setFormFields([]); }}
                        className="btn btn-outline"
                    >
                        Start Again
                    </button>
                </div>
            )}
        </div>
    );
}
