"""add_core_data_models

Revision ID: 821a9d7e6e5a
Revises: 
Create Date: 2026-02-28 00:39:13.701259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821a9d7e6e5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('office_name', sa.String(length=255), nullable=False),
    sa.Column('office_code', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('escalation_threshold', sa.Float(), nullable=False),
    sa.Column('supported_languages', sa.JSON(), nullable=False),
    sa.Column('processing_rules', sa.JSON(), nullable=False),
    sa.Column('contact_info', sa.JSON(), nullable=False),
    sa.Column('operating_hours', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('office_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_office_configs_office_code'), ['office_code'], unique=True)

    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('accessibility_needs', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_profiles_id'), ['id'], unique=False)

    op.create_table('form_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('form_name', sa.String(length=255), nullable=False),
    sa.Column('form_code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_templates_form_code'), ['form_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_templates_office_id'), ['office_id'], unique=False)

    op.create_table('user_auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('user_auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_auth_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('form_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('office_type', sa.String(length=100), nullable=False),
    sa.Column('form_type', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_sessions_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('assistance_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('office_id', sa.String(length=36), nullable=False),
    sa.Column('form_type', sa.String(length=100), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('session_snapshot', sa.JSON(), nullable=False),
    sa.Column('assigned_officer', sa.String(length=255), nullable=True),
    sa.Column('officer_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['form_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistance_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistance_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistance_receipts_office_id'), ['office_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistance_receipts_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assistance_receipts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistance_receipts_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['form_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_session_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('assistance_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistance_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_assistance_receipts_status'))
        batch_op.drop_index(batch_op.f('ix_assistance_receipts_session_id'))
        batch_op.drop_index(batch_op.f('ix_assistance_receipts_office_id'))
        batch_op.drop_index(batch_op.f('ix_assistance_receipts_id'))

    op.drop_table('assistance_receipts')
    with op.batch_alter_table('form_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_form_sessions_template_id'))
        batch_op.drop_index(batch_op.f('ix_form_sessions_id'))

    op.drop_table('form_sessions')
    with op.batch_alter_table('user_auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_auth_sessions_id'))

    op.drop_table('user_auth_sessions')
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_templates_office_id'))
        batch_op.drop_index(batch_op.f('ix_form_templates_id'))
        batch_op.drop_index(batch_op.f('ix_form_templates_form_code'))

    op.drop_table('form_templates')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_email'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('office_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_configs_office_code'))
        batch_op.drop_index(batch_op.f('ix_office_configs_id'))

    op.drop_table('office_configs')
    # ### end Alembic commands ###
